[build-system]
requires = ["setuptools>=44", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
	write_to = "ctypesgen/VERSION"
	write_to_template = "{version}"

[tool.black]
    line-length = 100
    target-version = [ "py37", "py38", "py39"]

